import { Component, OnInit } from '@angular/core';
import { Vehicule } from 'src/app/core/models/vehicule';

@Component({
  selector: 'app-creation',
  templateUrl: './creation-devis.component.html',
  styleUrls: ['./creation-devis.component.css'],
})
export class CreationDevisComponent implements OnInit {
  vehicules: Vehicule[] = [
    {
      id: 1,
      photo: '',
      marque: 'Renault',
      modele: 'super 5',
      annee: '1995',
      couleur: 'bleu',
      quantite: 10,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 1,
      photo: '',
      marque: 'Renault',
      modele: 'super 5',
      annee: '1995',
      couleur: 'bleu',
      quantite: 10,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
    {
      id: 2,
      photo: '',
      marque: 'Citroën',
      modele: 'picasso',
      annee: '2018',
      couleur: 'rouge',
      quantite: 1,
      prixHT: 3500.99,
    },
  ];
  constructor() {}

  ngOnInit(): void {}
}
